{
  imports = [
    ./neovim.nix
    ./yazi.nix
    ./spotify.nix
    ./vesktop.nix
    ./git.nix
    ./todoist.nix
    ./zsh.nix
    ./beeper.nix
    ./steam.nix
    ./firefox.nix
    ./ghostty.nix
    ./hyprland.nix
    ./thunderbird.nix
    ./bitwarden.nix
    ./mullvad.nix
    ./vpn.nix
    ./tmux.nix
  ];
}
